Run Nginx & Django throught https
TheSecretOrganization/ft_transcendence pull request #34
Opened 2024-08-10 14:40 UTC by Neffi42

2024-08-10 19:49 UTC, antoineverin requested changes

2024-08-10 19:49 UTC, antoineverin commented on .env.template
> +BASE_URL= # https//${HOSTNAME}.com
Missing `:` in https://

2024-08-10 19:49 UTC, antoineverin commented on django/conf/certs.sh
> +chmod 644 /etc/ssl/private/${HOSTNAME}.key /etc/ssl/certs/${HOSTNAME}.crt
Could be both on the same directory?

2024-08-10 19:49 UTC, antoineverin commented on docker-compose.yml
> +      - public-keys:/etc/ssl/certs/
Could use one volume with the parent directory

2024-08-10 20:12 UTC, Neffi42 commented on .env.template
> +BASE_URL= # https//${HOSTNAME}.com
oops

2024-08-10 20:12 UTC, Neffi42 commented on django/conf/certs.sh
> +chmod 644 /etc/ssl/private/${HOSTNAME}.key /etc/ssl/certs/${HOSTNAME}.crt
they could for sure

2024-08-12 08:10 UTC, antoineverin approved these changes

2024-08-12 08:10 UTC, merged